module.exports = {
    Fact: require("./fact"),
    Pic: require("./pic"),
    Joke: require("./joke"),
    Eight: require("./8ball"),
    Lore: require("./lore"),
    Role: require("./role"),
    Role2: require("./role2"),
    Help: require("./help"),
    Misc: require("./misc"),
    Intimidate: require("./intimidate"),
    Attattat: require("./attattat"),
    Train: require("./train"),
    Anthem: require("./anthem"),
    Great: require("./great"),
};
