module.exports = {
    Fact: require("./main/fact"),
    Pic: require("./main/pic"),
    Joke: require("./main/joke"),
    Eight: require("./main/8ball"),
    Lore: require("./main/lore"),
    Role: require("./main/role"),
    Role2: require("./main/role2"),
    Help: require("./main/help"),
    Author: require("./main/author"),
    Misc: require("./misc/misc"),
    Intimidate: require("./misc/intimidate"),
    Attattat: require("./misc/attattat"),
    Train: require("./misc/train"),
    Anthem: require("./misc/anthem"),
    Great: require("./misc/great"),
    Version: require("./misc/version"),
};
